server:
  port: 8765

spring:
  application:
    name: octo-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.221.213.251:8761/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  routes: 
    octo-auth:
      path: /octo-auth/**
      sensitiveHeaders: 
      serviceId: octo-auth
    octo-user-management-service:
      path: /octo-user-management-service/**
      sensitiveHeaders:
      serviceId: octo-user-management-service
	octo-board-service:
      path: /octo-board-service/**
      sensitiveHeaders:
      serviceId: octo-board-service
	octo-story-service:
      path: /octo-story-service/**
      sensitiveHeaders:
      serviceId: octo-story-service
	octo-story-history-service:
      path: /octo-story-history-service/**
      sensitiveHeaders:
      serviceId: octo-story-history-service
	octo-task-service:
      path: /octo-task-service/**
      sensitiveHeaders:
      serviceId: octo-task-service