# Story event history service
# used by chart service
spring: 
  application: 
    name: octo-story-history-service
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
  cloud:
    stream:
      bindings:
        input:
          destination: updatestorymessage
    default:
      contentType: application/json
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.cjcqerm3c0hj.us-east-2.rds.amazonaws.com:1521:ORCL
    username: story_history_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 12500
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.217.124.245:8761/eureka/,http://18.217.124.245:8762/eureka/
  instance:
    instanceId: ${spring.application.name}
security:
  oauth2:
    resource:
      accessTokenUri: http://18.217.124.245:8090/oauth/check_token
      userAuthorizationUri: http://18.217.124.245:8090/oauth/authorize
      userInfoUri: http://18.217.124.245:8090/user
      jwt:
        keyUri: http://18.217.124.245:8090/oauth/token_key