spring:
  application:
    name: octo-user-management-service
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.cjcqerm3c0hj.us-east-2.rds.amazonaws.com:1521:ORCL
    username: system_user_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 8099
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}
security:
 oauth2:
   resource:
     accessTokenUri: http://localhost:8090/auth/oauth/check_token
     userAuthorizationUri: http://localhost:8090/auth/oauth/authorize
     userInfoUri: http://localhost:8090/auth/user
     jwt:
       keyUri: http://localhost:8090/auth/oauth/token_key	

