#user-management-service
spring:
  application:
    name: octo-user-management-service
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.crwx5goxs3em.us-east-2.rds.amazonaws.com:1521:ORCL
    username: system_user_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 10001
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:8090/oauth/check_token
      userAuthorizationUri: http://localhost:8090/oauth/authorize
      userInfoUri: http://localhost:8090/user
      jwt:
        keyUri: http://localhost:8090/oauth/token_key
