server:
  port: 8765

spring:
  application:
    name: octo-zuul

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

zuul:
  routes: 
    octo-auth:
      path: /octo-auth/**
      sensitiveHeaders: 
      serviceId: octo-auth