spring:
  application:
    name: octo-story-service

  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672  
  cloud:
    stream:
      bindings:
        UpdateStoryMessageSource:
          destination: updatestorymessage
    default:
      contentType: application/json

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.cjcqerm3c0hj.us-east-2.rds.amazonaws.com:1521:ORCL
    username: story_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 12000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
security:
  oauth2:
    resource:
      accessTokenUri: http://localhost:8090/oauth/check_token
      userAuthorizationUri: http://localhost:8090/oauth/authorize
      userInfoUri: http://localhost:8090/user
      jwt:
        keyUri: http://localhost:8090/oauth/token_key
