spring:
 application:
   name: octo-auth
  mvc:
   dispatchOptionsRequest: true

server:
  port: 8090
 datasource:
   url: jdbc:oracle:thin:@octocat.crwx5goxs3em.us-east-2.rds.amazonaws.com:1521:ORCL
   username: system_user_db
   password: p4ssw0rd
   driverClassName: oracle.jdbc.OracleDriver
   tomcat:
     initial-size: 1

keystore:
 password: drunkenOctopus

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.221.213.251:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: 18.221.213.251:8090