spring:
  mvc:
    dispatchOptionsRequest: true
  application:
    name: octo-auth
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@orcl.c2jaeyvx2hsp.us-east-1.rds.amazonaws.com:1521:ORCL
    username: system_user_db
    password: p4ssw0rd
    driverClassName: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 8090
keystore:
  password: drunkenOctopus      
  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#      defaultZone: http://${DOCKER_HOST_IP}:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/