spring:
  application:
    name: octo-story-service
  rabbitmq:
    host: localhost
    password: guest
    username: guest
    port: 5672
  cloud:
    stream:
      bindings:
        input:
          destination: updatestorymessage
    default:
      contentType: application/json
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.cjcqerm3c0hj.us-east-2.rds.amazonaws.com:1521:ORCL
    username: story_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 5
server:
  port: 0
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.int}