#Board Service
spring:
  application:
    name: octo-board-management-service
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    database: ORACLE
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:oracle:thin:@octocat.cjcqerm3c0hj.us-east-2.rds.amazonaws.com:1521:ORCL
    username: scrum_board_db
    password: p4ssw0rd
    driver-class-name: oracle.jdbc.OracleDriver
    tomcat:
      initial-size: 1
server:
  port: 11000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://18.221.213.251:8761/eureka/
  instance:
    instanceId: ${spring.application.name}
    hostname: 18.221.213.251:11000
security:
  oauth2:
    resource:
      accessTokenUri: http://18.221.213.251:8090/auth/oauth/check_token
      userAuthorizationUri: http://18.221.213.251:8090/auth/oauth/authorize
      userInfoUri: http://18.221.213.251:8090/auth/user
      jwt:
        keyUri: http://18.221.213.251:8090/auth/oauth/token_key

